/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define PAGE_SIZE 4096
#define NAME_LEN 32
#define IP_LEN 16

struct page_t {
	u_int size;
	char addr[PAGE_SIZE];
};
typedef struct page_t page_t;

struct pageid_t {
	char name[NAME_LEN];
	u_int size;
};
typedef struct pageid_t pageid_t;

struct request_t {
	pageid_t pageid;
	mode_t mode;
};
typedef struct request_t request_t;

enum mode_t {
	NA = 0,
	RO = 1,
	RW = 2,
};
typedef enum mode_t mode_t;

#define PSU_DSM 0x20002234
#define PSU_DSM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PSU_DSM_PAGE_FIND 1
extern  int * psu_dsm_page_find_1(pageid_t *, CLIENT *);
extern  int * psu_dsm_page_find_1_svc(pageid_t *, struct svc_req *);
#define PSU_DSM_PAGE_CREAT 2
extern  int * psu_dsm_page_creat_1(page_id *, CLIENT *);
extern  int * psu_dsm_page_creat_1_svc(page_id *, struct svc_req *);
#define PSU_DSM_PAGE_UPDATE 3
extern  int * psu_dsm_page_update_1(request_t *, CLIENT *);
extern  int * psu_dsm_page_update_1_svc(request_t *, struct svc_req *);
#define PSU_DSM_PAGE_REQUEST 4
extern  page_t * psu_dsm_page_request_1(request_t *, CLIENT *);
extern  page_t * psu_dsm_page_request_1_svc(request_t *, struct svc_req *);
#define PSU_DSM_PAGE_FETCH 5
extern  page_t * psu_dsm_page_fetch_1(request_t *, CLIENT *);
extern  page_t * psu_dsm_page_fetch_1_svc(request_t *, struct svc_req *);
#define PSU_DSM_PAGE_ACK 6
extern  void * psu_dsm_page_ack_1(pageid_t *, CLIENT *);
extern  void * psu_dsm_page_ack_1_svc(pageid_t *, struct svc_req *);
extern int psu_dsm_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PSU_DSM_PAGE_FIND 1
extern  int * psu_dsm_page_find_1();
extern  int * psu_dsm_page_find_1_svc();
#define PSU_DSM_PAGE_CREAT 2
extern  int * psu_dsm_page_creat_1();
extern  int * psu_dsm_page_creat_1_svc();
#define PSU_DSM_PAGE_UPDATE 3
extern  int * psu_dsm_page_update_1();
extern  int * psu_dsm_page_update_1_svc();
#define PSU_DSM_PAGE_REQUEST 4
extern  page_t * psu_dsm_page_request_1();
extern  page_t * psu_dsm_page_request_1_svc();
#define PSU_DSM_PAGE_FETCH 5
extern  page_t * psu_dsm_page_fetch_1();
extern  page_t * psu_dsm_page_fetch_1_svc();
#define PSU_DSM_PAGE_ACK 6
extern  void * psu_dsm_page_ack_1();
extern  void * psu_dsm_page_ack_1_svc();
extern int psu_dsm_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_page_t (XDR *, page_t*);
extern  bool_t xdr_pageid_t (XDR *, pageid_t*);
extern  bool_t xdr_request_t (XDR *, request_t*);
extern  bool_t xdr_mode_t (XDR *, mode_t*);

#else /* K&R C */
extern bool_t xdr_page_t ();
extern bool_t xdr_pageid_t ();
extern bool_t xdr_request_t ();
extern bool_t xdr_mode_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
