
# This is a template Makefile generated by rpcgen

# Parameters


# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl
RPCGENFLAGS = 

# Targets 

all : server client

server: psu_dsm_msg.h psu_dsm_svc.c psu_dsm_server.c psu_dsm_clnt.c psu_dsm_xdr.c util.c util.h
	gcc -o server psu_dsm_svc.c psu_dsm_server.c psu_dsm_clnt.c psu_dsm_xdr.c util.c -lnsl -lrt

client: psu_dsm_msg.h psu_dsm_server.c psu_dsm.c psu_dsm_clnt.c psu_dsm_xdr.c util.c util.h
	gcc -o client psu_dsm_server.c psu_dsm.c psu_dsm_clnt.c psu_dsm_xdr.c util.c -lnsl -lrt


 clean:
	rm server client

