
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = client
SERVER = server

SOURCES_SVC.c = psu_dsm_msg_svc.c psu_dsm_msg_server.c psu_dsm_msg_xdr.c psu_dsm_msg_clnt.c util.c
SOURCES_SVC.h = psu_dsm_msg_svc.h util.h
SOURCES_CLNT.c = psu_dsm_msg_clnt.c psu_dsm.c psu_dsm_msg_xdr.c util.c test.c
SOURCES_CLNT.h = util.h

OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o)
OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g 
LDLIBS += -lnsl -lrt
RPCGENFLAGS = 

# Targets 

all : $(CLIENT) $(SERVER)


$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h)

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h)

$(CLIENT) : $(OBJECTS_CLNT) 
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLNT) $(LDLIBS) 

$(SERVER) : $(OBJECTS_SVC) 
	$(LINK.c) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 rm *.o server client

