/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "psu_dsm_msg.h"

bool_t
xdr_page_t (XDR *xdrs, page_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->addr, PAGESIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pageid_t (XDR *xdrs, pageid_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
