/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "psu_dsm_msg.h"

static int
search_dir(pageid_t page)
{
	dir_t *dirp = dir;
	while(dirp != NULL){
		if(strncmp(dirp->dirent.name, page.name, MAXNAME) == 0){
			return 1;
		}
		else{
			return 0;
		}
      	}
	return 0;
}

static int
insert_dir(pageid_t page)
{
	dir_t *dirp = dir;
	while(dirp != NULL){
		dirp = dirp->next;	
      	}

	dir_t *new = malloc(sizeof(dir_t));
	if(new == NULL){
		return 0;
	}
	
	strncmp(new->dirent.name, page.name, MAXNAME);
	int i;
	for(i = 0; i < MAXSERV; i++){
		new->dirent.pbits[i] = 0;
	}
	new->dirent.stat = NA;
	if(pthread_mutex_init(&new->dirent.lock, NULL) != 0){
		perror("mutex init failed.\n");
		return 0;
	}		 

	dirp->next = new;
	new->next = NULL;
	return 1;
}

int *
psu_dsm_page_find_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = search_dir(*argp);

	return &result;
}

int *
psu_dsm_page_creat_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	CLIENT *clnt;
	int *result_1;

	int i;
	// if page already exists, return 1 (success).
	for(i = 0; i < nserver; i++){
		clnt = clnt_create (server[i], PSU_DSM, PSU_DSM_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (server[i]);
			exit (1);
		}

		result_1 = psu_dsm_page_find_1(argp, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		if(*result_1 == 1){
			result = 1;
    			return &result;
		}
	}
	
	// page doesn't exist, create on local server.
	if(insert_dir(*argp) == 1)
		result = 1;
	else 
		result = 0;	
	return &result;
}

int *
psu_dsm_page_update_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

page_t *
psu_dsm_page_fetch_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static page_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
