/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "psu_dsm_msg.h"
#include "util.h"
int nserver;
serverid_t server[MAX_SERV];
dir_t *dir;
dsm_t *dsm;


// search if page is inside local dir
// return 1 if found, 0 if not found
int
search_dir(pageid_t page)
{
	dir_t *dirp = dir;
	while(dirp != NULL){
		if(strncmp(dirp->entry.page.name, page.name, NAME_LEN) == 0){
			return 1;
		}
		dirp = dirp->next;
      	}
	return 0;
}

int
print_dir()
{
	dir_t *dirp = dir;
	printf("dir = \n");
	while(dirp != NULL){
		printf("host %s\n", dirp->entry.page.name);
		dirp = dirp->next;
      	}
}
// insert a page into local dir
// return 1 if success, 0 if fail
int
insert_dir(pageid_t page)
{
	printf("insert_dir called.\n");
	dir_t *dirp = dir;
	dir_t **dirpp = &dir;
	while(dirp != NULL){
		dirpp = &((*dirpp)->next);
		dirp = dirp->next;	
      	}

	dir_t *new = malloc(sizeof(dir_t));
	if(new == NULL){
		return 0;
	}
	
	strncpy(new->entry.page.name, page.name, NAME_LEN);
	new->entry.page.size = page.size;
	int i;
	for(i = 0; i < MAX_SERV; i++){
		new->entry.pbits[i] = 0;
	}
}


int *
psu_dsm_page_find_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;
	result = search_dir(*argp);
	printf("RPC call page_find(); return %d\n", result);
	return &result;
}

int *
psu_dsm_page_creat_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static int  result;
	result = search_dir(*argp);
	printf("RPC call page_creat(); return %d\n", result);
	return &result;
}


int *
psu_dsm_page_update_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

page_t *
psu_dsm_page_request_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static page_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

page_t *
psu_dsm_page_fetch_1_svc(request_t *argp, struct svc_req *rqstp)
{
	static page_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
psu_dsm_page_ack_1_svc(pageid_t *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}
